"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.menuSeedData = void 0;
const base = {
    component: "",
    rank: null,
    redirect: "",
    icon: "",
    extraIcon: "",
    enterTransition: "",
    leaveTransition: "",
    activePath: "",
    auths: "",
    frameSrc: "",
    frameLoading: true,
    keepAlive: false,
    hiddenTag: false,
    fixedTag: false,
    showLink: true,
    showParent: false,
};
exports.menuSeedData = [
    { ...base, id: 100, parentId: 0, menuType: 0, title: "menus.pureExternalPage", name: "PureIframe", path: "/iframe", rank: 7, icon: "ri:links-fill" },
    { ...base, id: 101, parentId: 100, menuType: 0, title: "menus.pureExternalDoc", name: "PureIframeExternal", path: "/iframe/external" },
    { ...base, id: 102, parentId: 101, menuType: 2, title: "menus.pureExternalLink", name: "https://pure-admin.cn/", path: "/external" },
    { ...base, id: 103, parentId: 101, menuType: 2, title: "menus.pureUtilsLink", name: "https://pure-admin-utils.netlify.app/", path: "/pureUtilsLink" },
    { ...base, id: 104, parentId: 100, menuType: 1, title: "menus.pureEmbeddedDoc", name: "PureIframeEmbedded", path: "/iframe/embedded" },
    { ...base, id: 105, parentId: 104, menuType: 1, title: "menus.pureEpDoc", name: "FrameEp", path: "/iframe/ep", frameSrc: "https://element-plus.org/zh-CN/", keepAlive: true },
    { ...base, id: 106, parentId: 104, menuType: 1, title: "menus.pureTailwindcssDoc", name: "FrameTailwindcss", path: "/iframe/tailwindcss", frameSrc: "https://tailwindcss.com/docs/installation", keepAlive: true },
    { ...base, id: 107, parentId: 104, menuType: 1, title: "menus.pureVueDoc", name: "FrameVue", path: "/iframe/vue3", frameSrc: "https://cn.vuejs.org/", keepAlive: true },
    { ...base, id: 108, parentId: 104, menuType: 1, title: "menus.pureViteDoc", name: "FrameVite", path: "/iframe/vite", frameSrc: "https://cn.vitejs.dev/", keepAlive: true },
    { ...base, id: 109, parentId: 104, menuType: 1, title: "menus.purePiniaDoc", name: "FramePinia", path: "/iframe/pinia", frameSrc: "https://pinia.vuejs.org/zh/index.html", keepAlive: true },
    { ...base, id: 110, parentId: 104, menuType: 1, title: "menus.pureRouterDoc", name: "FrameRouter", path: "/iframe/vue-router", frameSrc: "https://router.vuejs.org/zh/", keepAlive: true },
    { ...base, id: 200, parentId: 0, menuType: 0, title: "menus.purePermission", name: "PurePermission", path: "/permission", rank: 9, icon: "ep:lollipop" },
    { ...base, id: 201, parentId: 200, menuType: 0, title: "menus.purePermissionPage", name: "PermissionPage", path: "/permission/page/index" },
    { ...base, id: 202, parentId: 200, menuType: 0, title: "menus.purePermissionButton", name: "PermissionButton", path: "/permission/button" },
    { ...base, id: 203, parentId: 202, menuType: 0, title: "menus.purePermissionButtonRouter", name: "PermissionButtonRouter", path: "/permission/button/router", component: "permission/button/index" },
    { ...base, id: 210, parentId: 203, menuType: 3, title: "鏂板", name: "", path: "", auths: "permission:btn:add" },
    { ...base, id: 211, parentId: 203, menuType: 3, title: "淇敼", name: "", path: "", auths: "permission:btn:edit" },
    { ...base, id: 212, parentId: 203, menuType: 3, title: "鍒犻櫎", name: "", path: "", auths: "permission:btn:delete" },
    { ...base, id: 204, parentId: 202, menuType: 0, title: "menus.purePermissionButtonLogin", name: "PermissionButtonLogin", path: "/permission/button/login", component: "permission/button/perms" },
    { ...base, id: 220, parentId: 204, menuType: 3, title: "鏂板", name: "", path: "", auths: "permission:btn:add" },
    { ...base, id: 221, parentId: 204, menuType: 3, title: "淇敼", name: "", path: "", auths: "permission:btn:edit" },
    { ...base, id: 222, parentId: 204, menuType: 3, title: "鍒犻櫎", name: "", path: "", auths: "permission:btn:delete" },
    { ...base, id: 300, parentId: 0, menuType: 0, title: "menus.pureSysManagement", name: "PureSystem", path: "/system", rank: 10, icon: "ri:settings-3-line" },
    { ...base, id: 301, parentId: 300, menuType: 0, title: "menus.pureUser", name: "SystemUser", path: "/system/user/index", icon: "ri:admin-line" },
    { ...base, id: 302, parentId: 300, menuType: 0, title: "menus.pureRole", name: "SystemRole", path: "/system/role/index", icon: "ri:admin-fill" },
    { ...base, id: 303, parentId: 300, menuType: 0, title: "menus.pureSystemMenu", name: "SystemMenu", path: "/system/menu/index", icon: "ep:menu" },
    { ...base, id: 304, parentId: 300, menuType: 0, title: "menus.pureDept", name: "SystemDept", path: "/system/dept/index", icon: "ri:git-branch-line" },
    { ...base, id: 305, parentId: 300, menuType: 0, title: "menus.pureSystemBasic", name: "SystemBasic", path: "/system/basic/index", component: "system/basic/index", icon: "ri:information-line" },
    { ...base, id: 308, parentId: 0, menuType: 0, title: "三方类库接口管理", name: "ThirdPartyManage", path: "/third-party", rank: 15, component: "system/third-party/layout", redirect: "/third-party/wechat", icon: "ri:apps-2-line" },
    { ...base, id: 311, parentId: 308, menuType: 0, title: "微信设置", name: "ThirdPartyWechat", path: "/third-party/wechat", component: "system/third-party/provider-page", icon: "ri:wechat-fill" },
    { ...base, id: 318, parentId: 311, menuType: 3, title: "微信公众号子页", name: "", path: "", auths: "third-party:wechat:mp" },
    { ...base, id: 312, parentId: 308, menuType: 0, title: "QQ 设置", name: "ThirdPartyQq", path: "/third-party/qq", component: "system/third-party/provider-page", icon: "ri:qq-fill" },
    { ...base, id: 313, parentId: 308, menuType: 0, title: "阿里云配置", name: "ThirdPartyAliyun", path: "/third-party/aliyun", component: "system/third-party/provider-page", icon: "ri:cloud-fill" },
    { ...base, id: 314, parentId: 308, menuType: 0, title: "七牛云配置", name: "ThirdPartyQiniu", path: "/third-party/qiniu", component: "system/third-party/provider-page", icon: "ri:database-2-fill" },
    { ...base, id: 315, parentId: 308, menuType: 0, title: "腾讯云配置", name: "ThirdPartyTencent", path: "/third-party/tencent", component: "system/third-party/provider-page", icon: "ri:cloud-windy-fill" },
    { ...base, id: 316, parentId: 308, menuType: 0, title: "AWS 配置", name: "ThirdPartyAws", path: "/third-party/aws", component: "system/third-party/provider-page", icon: "ri:amazon-fill" },
    { ...base, id: 317, parentId: 308, menuType: 0, title: "自定义配置", name: "ThirdPartyCustom", path: "/third-party/custom", component: "system/third-party/provider-page", icon: "ri:settings-2-fill" },
    { ...base, id: 400, parentId: 0, menuType: 0, title: "menus.pureSysMonitor", name: "PureMonitor", path: "/monitor", rank: 11, icon: "ep:monitor" },
    { ...base, id: 401, parentId: 400, menuType: 0, title: "menus.pureOnlineUser", name: "OnlineUser", path: "/monitor/online-user", component: "monitor/online/index", icon: "ri:user-voice-line" },
    { ...base, id: 402, parentId: 400, menuType: 0, title: "menus.pureLoginLog", name: "LoginLog", path: "/monitor/login-logs", component: "monitor/logs/login/index", icon: "ri:window-line" },
    { ...base, id: 403, parentId: 400, menuType: 0, title: "menus.pureOperationLog", name: "OperationLog", path: "/monitor/operation-logs", component: "monitor/logs/operation/index", icon: "ri:history-fill" },
    { ...base, id: 404, parentId: 400, menuType: 0, title: "menus.pureSystemLog", name: "SystemLog", path: "/monitor/system-logs", component: "monitor/logs/system/index", icon: "ri:file-search-line" },
    { ...base, id: 500, parentId: 0, menuType: 0, title: "menus.pureTabs", name: "PureTabs", path: "/tabs", rank: 12, icon: "ri:bookmark-2-line" },
    { ...base, id: 501, parentId: 500, menuType: 0, title: "menus.pureTabs", name: "Tabs", path: "/tabs/index" },
    { ...base, id: 502, parentId: 500, menuType: 0, title: "query浼犲弬妯″紡", name: "TabQueryDetail", path: "/tabs/query-detail", activePath: "/tabs/index", showLink: false },
    { ...base, id: 503, parentId: 500, menuType: 0, title: "params浼犲弬妯″紡", name: "TabParamsDetail", path: "/tabs/params-detail/:id", component: "params-detail", activePath: "/tabs/index", showLink: false },
    { ...base, id: 600, parentId: 0, menuType: 0, title: "轮播图管理", name: "CarouselManage", path: "/carousel", rank: 13, icon: "ep:picture-filled" },
    { ...base, id: 601, parentId: 600, menuType: 0, title: "资源管理", name: "CarouselResource", path: "/carousel/resource", component: "carousel/resource/index", icon: "ep:files" },
    { ...base, id: 602, parentId: 600, menuType: 0, title: "类目管理", name: "CarouselCategory", path: "/carousel/category", component: "carousel/category/index", icon: "ep:collection-tag" },
    { ...base, id: 610, parentId: 0, menuType: 0, title: "资源系统", name: "ResourceSystemManage", path: "/resource-system", rank: 14, icon: "ep:box" },
    { ...base, id: 611, parentId: 610, menuType: 0, title: "资源管理", name: "ResourceSystemResource", path: "/resource-system/resource", component: "resource-system/resource/index", icon: "ep:files" },
    { ...base, id: 612, parentId: 610, menuType: 0, title: "类目管理", name: "ResourceSystemCategory", path: "/resource-system/category", component: "resource-system/category/index", icon: "ep:collection-tag" },
    { ...base, id: 613, parentId: 610, menuType: 0, title: "存储设置", name: "ResourceSystemStorage", path: "/resource-system/storage", component: "resource-system/storage/index", icon: "ep:coin" },
    { ...base, id: 620, parentId: 0, menuType: 0, title: "表单管理", name: "SurveyManage", path: "/survey", rank: 16, icon: "ri:file-list-3-line" },
    { ...base, id: 621, parentId: 620, menuType: 0, title: "问卷调查列表", name: "SurveyList", path: "/survey/list", component: "survey/list/index", icon: "ri:list-check-3" },
    { ...base, id: 623, parentId: 620, menuType: 0, title: "自定义表单工作流", name: "SurveyWorkflow", path: "/survey/workflow", component: "survey/workflow/index", icon: "ri:git-branch-line" },
    { ...base, id: 630, parentId: 0, menuType: 0, title: "Agent监控", name: "AgentMonitorRoot", path: "/agent-monitor", rank: 17, icon: "ri:radar-line", redirect: "/agent-monitor/index" },
    { ...base, id: 631, parentId: 630, menuType: 0, title: "Agent监控台", name: "AgentMonitor", path: "/agent-monitor/index", component: "monitor/agent/index", icon: "ri:pulse-line", showParent: true },
];
