"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = __importDefault(require("express"));
const auth_1 = __importDefault(require("./auth"));
const account_1 = __importDefault(require("./account"));
const asyncRoute_1 = __importDefault(require("./asyncRoute"));
const menu_1 = __importDefault(require("./menu"));
const role_1 = __importDefault(require("./role"));
const dept_1 = __importDefault(require("./dept"));
const user_1 = __importDefault(require("./user"));
const monitor_1 = __importDefault(require("./monitor"));
const carousel_1 = __importDefault(require("./carousel"));
const resourceSystem_1 = __importDefault(require("./resourceSystem"));
const system_1 = __importDefault(require("./system"));
const survey_1 = __importDefault(require("./survey"));
const formWorkflow_1 = __importDefault(require("./formWorkflow"));
const authSession_1 = require("../middleware/authSession");
const permissionAccess_1 = require("../middleware/permissionAccess");
const router = express_1.default.Router();
router.use("/", auth_1.default);
router.use(authSession_1.authSessionMiddleware);
router.use(permissionAccess_1.permissionAccessMiddleware);
router.use("/", asyncRoute_1.default);
router.use("/account", account_1.default);
router.use("/menu", menu_1.default);
router.use("/role", role_1.default);
router.use("/dept", dept_1.default);
router.use("/user", user_1.default);
router.use("/monitor", monitor_1.default);
router.use("/carousel", carousel_1.default);
router.use("/resource-system", resourceSystem_1.default);
router.use("/system", system_1.default);
router.use("/survey", survey_1.default);
router.use("/form-workflow", formWorkflow_1.default);
exports.default = router;
